In [1]:
# The following piece of code gives the opportunity to show multiple outputs
# in one cell:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


# Colorful outputs
class bcolors:
    RED       = '\033[91m'
    OKBLUE    = '\033[94m'
    BOLD      = '\033[1m'
    UNDERLINE = '\033[4m'
    ENDC      = '\033[0m'

- The objective of this exercise is to understand the notions of underfitting and overfitting. Using cross-validation on simulated data.

##### Synthetic data
- I have generated 100 points equally distanced from -20 to 20 and save them in a `numpy` array `x`.
- I have created a new numpy array `y` defined as $y_i=\mathrm{sin}(x_i) + 0.05 x_i^3 + \varepsilon_i$ where $\varepsilon_i \sim \mathcal{N}(0,100^2)$, for $i=1,...,100$.
- I have plotted the scatter plot of `x` and `y`.
##### Underfitting vs. Overfitting
-I have fitted a linear regression model and called it `model1` : $y=\beta_0 + \beta_1 x$ and added the fitted line over the scatter plot and computed the mean squared error of `model1`( `sklearn.metrics.mean_squared_error`).
- A polynomial regression model is fitted with degree 5 and called `model2` : $y=\beta_0 + \beta_1 x + \beta_2 x^2 + ... + \beta_5 x^5$ (`sklearn.preprocessing.PolynomialFeatures` in order to create a **new** input array that includes $x^0$, $x^1$, $x^2$, $x^3$ ...).
- The fitted curve is added over the scatter plot and compared `model2` and `model1`.
- I have compute the mean squared error of `model2`.
- I have fitted a polynomial regression model with degree 20 and called it `model3` : $y=\beta_0 + \beta_1 x + \beta_2 x^2 + ... + \beta_{20} x^{20}$.
- I have added the fitted curve over the scatter plot and compared the models.

##### Cross-Validation
- Using $10$-fold cross-validation, I have computed the **averaged validation** mean squared errors for all possible polynomial models by varying the degree of the polynomial model from $1$ to $20$.

##### LASSO
- Using $10$-fold cross-validation and the LASSO regularization, I have fitted the polynomial model with degree 20 and call it `model4`.

In [2]:
##Synthetic data
#Generate 100 points
import numpy as np
import math
p1=-20
p2=20
parts=100
x=np.linspace(p1, p2, parts)
#Create y
y=[]
eps=np.random.normal(0,100, 100)
for i in range(0,100):
    y_i=math.sin(x[i])+(0.05*x[i]**3)+eps[i]
    y.append(y_i)
#Plot Scatter of x,y
import matplotlib.pyplot as plt
plt.figure(1)
plt.scatter(x,y)
#We can fit a linear model over data, however, to be more accurate it is better to use a nonlinear model

##Underfitting vs. Overfitting
import pandas as pd
x = pd.DataFrame(data=x)
y = pd.DataFrame(data=y)
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
# fit the model and feed the data
lr.fit(X = x, y = y)
# regression parameters intercept is beta0 and coef_ is beta1
print(lr.intercept_, lr.coef_)
plt.figure(2)
plt.plot(x, y, 'or', mfc='none');
# add a regression line
plt.plot(x, lr.intercept_+lr.coef_*x, "-b");
plt.xlabel('x');
plt.ylabel('y');
#Mean Squard Error
model1=lr.intercept_+lr.coef_*x
import sklearn
print(sklearn.metrics.mean_squared_error(y,model1))
##Fit a degree five model
x=np.linspace(p1, p2, parts)
#Create y
y=[]
eps=np.random.normal(0,100, 100)
for i in range(0,100):
    y_i=math.sin(x[i])+(0.05*x[i]**3)+eps[i]
    y.append(y_i)
import numpy.polynomial.polynomial as poly
np.polyfit(x,y,5)
coefs = poly.polyfit(x, y, 5)
model2 = poly.polyval(x, coefs)
plt.plot(x, model2)
print(sklearn.metrics.mean_squared_error(y,model2))
##Fit a degree 20 model
x=np.linspace(p1, p2, parts)
#Create y
y=[]
eps=np.random.normal(0,100, 100)
for i in range(0,100):
    y_i=math.sin(x[i])+(0.05*x[i]**3)+eps[i]
    y.append(y_i)
import numpy.polynomial.polynomial as poly
np.polyfit(x,y,20)
coefs = poly.polyfit(x, y, 20)
model3 = poly.polyval(x, coefs)
plt.plot(x, model3)
print(sklearn.metrics.mean_squared_error(y,model2))
##compute the error for all possible degrees
x=np.linspace(p1, p2, parts)
#Create y
y=[]
eps=np.random.normal(0,100, 100)
for i in range(0,100):
    y_i=math.sin(x[i])+(0.05*x[i]**3)+eps[i]
    y.append(y_i)
import numpy.polynomial.polynomial as poly
plt.figure(3)
error=[]
for j in range(1,21):
    np.polyfit(x,y,j)
    coefs = poly.polyfit(x, y, j)
    model = poly.polyval(x, coefs)
    #plt.plot(x, model)
    error.append(sklearn.metrics.mean_squared_error(y,model))
    plt.scatter(j, sklearn.metrics.mean_squared_error(y,model))
plt.xlabel('Degree of Polynomial');
plt.ylabel('Error');
#Lasso and fitmodel
from sklearn import linear_model
kk=np.linspace(0.04, 0.09, 10)
plt.figure(4)
for k in kk:
 reg = linear_model.Lasso(alpha=k,normalize=True)
 x = pd.DataFrame(data=x)
 reg.fit(x,model3)
 model4=reg.predict(x)
 #plt.plot(x,model3)
 #plt.plot(x,model4)
 #print("R Squared:", reg.score(x, model3))
 from sklearn.metrics import mean_squared_error
# print("MSE:", mean_squared_error(model3, model4))
 plt.scatter(k,reg.score(x, model3))
#I select alpha=0.04 to have the highest R-square

## 10-fold CV, with shuffle
from sklearn import model_selection
import numpy as np
# 10-fold CV, with shuffle
y=np.reshape(y,(100,1))
y = pd.DataFrame(data=y)
print("y")
print(y)
n = len(x)
kf_10 = model_selection.KFold(n_splits=10, shuffle=True)

regr = LinearRegression()
r2 = []

# Calculate R2 with only the intercept 
#(no principal components in regression)
score = model_selection.cross_val_score(regr, np.ones((n,1)), y.iloc[:,0], cv=kf_10, scoring='r2').mean()    
r2.append(score)

# Calculate R2 using CV for the 5 principle components, 
#adding one component at the time.
from sklearn.preprocessing import PolynomialFeatures

for i in np.arange(1, 6):
    score = model_selection.cross_val_score(regr, PolynomialFeatures(i).fit_transform(x), y, cv=kf_10, scoring='r2').mean()
    r2.append(score)
    
# Plot results
plt.figure(5)
plt.plot(r2, '-v')
plt.xlabel('Number of principal components in regression')
plt.ylabel('R Squared')

<Figure size 640x480 with 0 Axes>

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

[3.66190349] [[11.95414299]]


<Figure size 640x480 with 0 Axes>

Text(0.5,0,'x')

Text(0,0.5,'y')

11241.151722037856


array([ 1.30171100e-05,  1.08153222e-03,  3.68977527e-02, -2.19195285e-01,
        8.76915658e-01, -1.04471377e+01])

8472.186068171914


array([-9.14300854e-20, -4.51973222e-19,  1.80759722e-16,  8.31429832e-16,
       -1.51774516e-13, -6.37172421e-13,  7.05742531e-11,  2.63524265e-10,
       -1.98806003e-08, -6.36916677e-08,  3.49137895e-06,  9.10666860e-06,
       -3.79909010e-04, -7.45679799e-04,  2.47121914e-02,  3.25890595e-02,
       -8.89852954e-01, -6.50400591e-01,  1.46406789e+01,  6.22182947e+00,
       -2.58169217e+01])

10818.22825627065


<Figure size 640x480 with 0 Axes>

array([12.25131576, -2.22021076])

array([  0.12650604,  12.25131576, -19.4284396 ])

array([  0.04169971,   0.12650604,   2.04256571, -19.4284396 ])

array([ 4.76878506e-05,  4.16997130e-02,  1.09831174e-01,  2.04256571e+00,
       -1.87482881e+01])

array([-4.43197765e-05,  4.76878506e-05,  6.17832657e-02,  1.09831174e-01,
        2.87630192e-01, -1.87482881e+01])

array([ 4.19017683e-06, -4.43197765e-05, -2.28185940e-03,  6.17832657e-02,
        4.26374135e-01,  2.87630192e-01, -2.48920958e+01])

array([ 4.71670500e-07,  4.19017683e-06, -3.54833875e-04, -2.28185940e-03,
        1.19296387e-01,  4.26374135e-01, -2.31597083e+00, -2.48920958e+01])

array([ 1.11231901e-07,  4.71670500e-07, -8.03882860e-05, -3.54833875e-04,
        1.75920251e-02,  1.19296387e-01, -1.04514754e+00, -2.31597083e+00,
       -8.24829847e+00])

array([-1.99190106e-08,  1.11231901e-07,  1.76449356e-05, -8.03882860e-05,
       -5.24837867e-03,  1.75920251e-02,  6.30004671e-01, -1.04514754e+00,
       -1.64868528e+01, -8.24829847e+00])

array([ 9.51461529e-10, -1.99190106e-08, -8.05664749e-07,  1.76449356e-05,
        2.26804150e-04, -5.24837867e-03, -2.40604930e-02,  6.30004671e-01,
        9.09562577e-01, -1.64868528e+01, -2.27011746e+01])

array([ 7.96468748e-11,  9.51461529e-10, -1.04737760e-07, -8.05664749e-07,
        5.03135608e-05,  2.26804150e-04, -1.07165318e-02, -2.40604930e-02,
        1.00042173e+00,  9.09562577e-01, -2.34345610e+01, -2.27011746e+01])

array([ 1.52499344e-12,  7.96468748e-11, -8.26588698e-10, -1.04737760e-07,
       -3.17251824e-08,  5.03135608e-05,  7.23746803e-05, -1.07165318e-02,
       -1.02250540e-02,  1.00042173e+00,  4.60089033e-01, -2.34345610e+01,
       -2.03614117e+01])

array([-2.96493541e-13,  1.52499344e-12,  4.55208022e-10, -8.26588698e-10,
       -2.87016325e-07, -3.17251824e-08,  9.25889147e-05,  7.23746803e-05,
       -1.54570153e-02, -1.02250540e-02,  1.22671610e+00,  4.60089033e-01,
       -2.64948560e+01, -2.03614117e+01])

array([ 3.45065343e-14, -2.96493541e-13, -4.56499364e-11,  4.55208022e-10,
        2.44289162e-08, -2.87016325e-07, -6.71100018e-06,  9.25889147e-05,
        9.75103541e-04, -1.54570153e-02, -6.80099171e-02,  1.22671610e+00,
        1.83791567e+00, -2.64948560e+01, -2.56797438e+01])

array([-1.31653611e-14,  3.45065343e-14,  1.90208920e-11, -4.56499364e-11,
       -1.08508507e-08,  2.44289162e-08,  3.07200654e-06, -6.71100018e-06,
       -4.39846186e-04,  9.75103541e-04,  2.76725389e-02, -6.80099171e-02,
       -3.05387660e-01,  1.83791567e+00, -1.08554293e+01, -2.56797438e+01])

array([ 2.72330435e-16, -1.31653611e-14, -3.92271848e-13,  1.90208920e-11,
        2.25393789e-10, -1.08508507e-08, -6.49549702e-08,  3.07200654e-06,
        9.56586192e-06, -4.39846186e-04, -6.28394237e-04,  2.76725389e-02,
        9.21646726e-03, -3.05387660e-01,  4.28686333e-01, -1.08554293e+01,
       -2.14889192e+01])

array([ 2.19679324e-17,  2.72330435e-16, -4.97782149e-14, -3.92271848e-13,
        4.40927464e-11,  2.25393789e-10, -1.99385413e-08, -6.49549702e-08,
        4.94278037e-06,  9.56586192e-06, -6.57607304e-04, -6.28394237e-04,
        4.10639245e-02,  9.21646725e-03, -6.73476151e-01,  4.28686333e-01,
       -7.92039129e+00, -2.14889192e+01])

array([-1.04251084e-17,  2.19679324e-17,  1.86811692e-14, -4.97782149e-14,
       -1.39105322e-11,  4.40927464e-11,  5.56699831e-09, -1.99385413e-08,
       -1.29207276e-06,  4.94278037e-06,  1.74697539e-04, -6.57607304e-04,
       -1.30706787e-02,  4.10639245e-02,  4.77066644e-01, -6.73476151e-01,
       -6.31394087e+00, -7.92039129e+00, -5.57953770e+00])

array([ 1.77861319e-18, -1.04251084e-17, -3.29446684e-15,  1.86811692e-14,
        2.54943121e-12, -1.39105322e-11, -1.06778871e-09,  5.56699831e-09,
        2.62113648e-07, -1.29207276e-06, -3.81950215e-05,  1.74697539e-04,
        3.20709418e-03, -1.30706787e-02, -1.45877310e-01,  4.77066644e-01,
        3.42133141e+00, -6.31394087e+00, -3.41129749e+01, -5.57953769e+00])

array([-1.06864653e-19,  1.77861319e-18,  1.99353796e-16, -3.29446684e-15,
       -1.56058779e-13,  2.54943121e-12,  6.65323519e-11, -1.06778871e-09,
       -1.67683266e-08,  2.62113648e-07,  2.53772897e-06, -3.81950215e-05,
       -2.24094843e-04,  3.20709418e-03,  1.07134274e-02, -1.45877310e-01,
       -2.40941305e-01,  3.42133141e+00,  2.06192433e+00, -3.41129749e+01,
       -2.16293238e+01])

Text(0.5,0,'Degree of Polynomial')

Text(0,0.5,'Error')

<Figure size 640x480 with 0 Axes>

Lasso(alpha=0.04, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=True, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

Lasso(alpha=0.04555555555555556, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=True, positive=False, precompute=False,
   random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

Lasso(alpha=0.05111111111111111, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=True, positive=False, precompute=False,
   random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

Lasso(alpha=0.056666666666666664, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=True, positive=False, precompute=False,
   random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

Lasso(alpha=0.06222222222222222, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=True, positive=False, precompute=False,
   random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

Lasso(alpha=0.06777777777777777, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=True, positive=False, precompute=False,
   random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

Lasso(alpha=0.07333333333333333, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=True, positive=False, precompute=False,
   random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

Lasso(alpha=0.07888888888888888, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=True, positive=False, precompute=False,
   random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

Lasso(alpha=0.08444444444444443, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=True, positive=False, precompute=False,
   random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

Lasso(alpha=0.09, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=True, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

y
             0
0  -214.296998
1  -129.437582
2  -582.346913
3  -369.926407
4  -316.293375
5  -267.736544
6  -189.542802
7  -235.511951
8  -235.993261
9  -137.251949
10 -339.674889
11 -192.961547
12 -117.831456
13 -242.155744
14  -52.365222
15 -114.275928
16    8.619030
17  -52.107157
18   39.757536
19  -70.812421
20  -25.020131
21  -79.047750
22 -419.863466
23  -55.506041
24  -19.735754
25 -261.190576
26 -121.863182
27 -240.049682
28  -26.234767
29 -109.623098
..         ...
70   66.292207
71   80.494865
72   68.635924
73   17.307834
74  169.157489
75  400.582003
76   36.269940
77  168.023248
78 -167.036652
79  -28.222998
80   97.165826
81  133.570698
82  371.169815
83  -25.622123
84  180.964236
85   81.205368
86  155.211743
87  128.732937
88  372.869401
89   62.783739
90  490.698355
91  100.696307
92  215.587252
93  311.321070
94  338.175580
95  223.028454
96  272.083914
97  419.514634
98  384.264205
99  438.284256

[100 rows x 1 columns]


<Figure size 640x480 with 0 Axes>

Text(0.5,0,'Number of principal components in regression')

Text(0,0.5,'R Squared')