In [1]:
# The following piece of code gives the opportunity to show multiple outputs
# in one cell:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


# Colorful outputs
class bcolors:
    RED       = '\033[91m'
    OKBLUE    = '\033[94m'
    BOLD      = '\033[1m'
    UNDERLINE = '\033[4m'
    ENDC      = '\033[0m'

- `Credit.csv` data from http://www-bcf.usc.edu/~gareth/ISL/Credit.csv is described using descriptive statistics such as measures of central tendancy, dispersion or association.
- The data is explored by vizualing it through various figures.
- Some variables of this dataset are **qualitative** and some are **quantitative**. A matrix is created $\mathbf{X}$ that includes only the following attributes:`Income`, `Limit`, `Rating`, `Cards`, `Age`, and `Education`.
- A binary variable is created `Balance_1500` which equals $1$ for each observation if `Balance` $> 1500$ for that observation and equals $0$ otherwise.
- Model is obtained for `Balance_1500` by the explanatory variables using the following models: 
    + logistic regression, 
    + linear discriminant, and 
    + quadratic discriminant.
- Coefficients are interpreted.    
- I have found the probability of (`Balance` $> 1500$), for the following values, using all three aforementionned methods:

|    Income    |    Limit     |     Rating     |    Cards     |      Age        |   Education   | 
|--------------|--------------|----------------|--------------|-----------------|---------------|
|      63      |    8100      |     600        |      4       |       30        |      13       |
|     186      |    13414     |     950        |      2       |       41        |      13       |

- Methods are compared.
    
- For each method, the confusion matrix, the accuracy score and the AUC using all observations are printed and compared. 
- The ROC Curve of the three methods are plotted on the same figure.

In [2]:
import pandas as pd
#2 Load the Data
filename = 'data/Credit.csv'
Credit = pd.read_csv(filename, usecols=[1, 2, 3,4,5,6,7,8,9,10,11])
Credit.head()
#3 Describe the Data
print(Credit.describe())
#4 Plot
import matplotlib.pyplot as plt
plt.figure(1,figsize=(22,22))
plt.subplot(10,1,1)
plt.plot(Credit['Income'], Credit['Balance'],'ro')
plt.ylabel('Balance vs Income')
plt.subplot(10,1,2)
plt.plot(Credit['Limit'], Credit['Balance'],'ro')
plt.ylabel('Balance vs Limit')
plt.subplot(10,1,3)
plt.plot(Credit['Rating'], Credit['Balance'],'ro')
plt.ylabel('Balance vs Rating')
plt.subplot(10,1,4)
plt.plot(Credit['Cards'], Credit['Balance'],'ro')
plt.ylabel('Balance vs Cards')
plt.subplot(10,1,5)
plt.plot(Credit['Age'], Credit['Balance'],'ro')
plt.ylabel('Balance vs Age')
plt.subplot(10,1,6)
plt.plot(Credit['Education'], Credit['Balance'],'ro')
plt.ylabel('Balance vs Education')
plt.subplot(10,1,7)
plt.plot(Credit['Gender'], Credit['Balance'],'ro')
plt.ylabel('Gender vs Education')
plt.subplot(10,1,8)
plt.plot(Credit['Student'], Credit['Balance'],'ro')
plt.ylabel('Student vs Education')
plt.subplot(10,1,9)
plt.plot(Credit['Married'], Credit['Balance'],'ro')
plt.ylabel('Married vs Education')
plt.subplot(10,1,10)
plt.plot(Credit['Ethnicity'], Credit['Balance'],'ro')
plt.ylabel('Ethnicity vs Education')
#Based on the plots we can see the balance is a variable of Income, limit and rating. However, it is not really dependent
#on cards, age, education, being married or student and ethnicity. We cannot see a trend in the last seven plots
#5 Create a Matrix X
X = pd.read_csv(filename, usecols=[1, 2, 3,4,5,6])
X.head()
#6
Balance_1500=[]
for i in Credit['Balance']:
 if i>1500:
  Balance_1500+=[1]
 else:
  Balance_1500+=[0]

#7 Model Balance_1500
#Logistic Regression
from sklearn.linear_model import LogisticRegression

X = X
y = Balance_1500

lr = LogisticRegression()
lr.fit(X, y)
print(lr.intercept_)
print(lr.coef_)
#linear discriminant
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
X = X
y = Balance_1500
lda = LinearDiscriminantAnalysis()
lda.fit(X,y)
#Quadratic discriminant
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis 
X = X
y = Balance_1500
qda = QuadraticDiscriminantAnalysis()
qda.fit(X,y)
#8
#Those coeffiecients for Income, Age and education are -0.00950572,  -0.05977501 and -0.35404606and ,respectively. We can see
#based on these coeffiecients the effect of education is more than age and after that is the income.
#9
#Logistic Regression

X_test_1=[[63,8100,600,4,30,13]]
y_pred_lr_1=lr.predict(X_test_1)
print("y_pred_lr_1:")
print(y_pred_lr_1)

y_pred_lda_1=lda.predict(X_test_1)
print("y_pred_lda_1:")
print(y_pred_lda_1)

y_pred_qda_1=lda.predict(X_test_1)
print("y_pred_qda_1:")
print(y_pred_qda_1)

X_test_2=[[186,13414,950,2,41,13]]
y_pred_lr_2=lr.predict(X_test_2)
print("y_pred_lr_2:")
print(y_pred_lr_2)

y_pred_lda_2=lda.predict(X_test_2)
print("y_pred_lda_2:")
print(y_pred_lda_2)

y_pred_qda_2=qda.predict(X_test_2)
print("y_pred_qda_2:")
print(y_pred_qda_2)

#10
#Print the confusion Matrix
from sklearn.metrics import confusion_matrix

y_pred = lr.predict(X)
print("confusion_matrix_lr")
print(confusion_matrix(y, y_pred))

y_pred = lda.predict(X)
print("confusion_matrix_lda")
print(confusion_matrix(y, y_pred))

y_pred = qda.predict(X)
print("confusion_matrix_qda")
print(confusion_matrix(y, y_pred))

#Accuracy Score

from sklearn.metrics import accuracy_score

y_pred = lr.predict(X)
print("accuracy_score_lr")
print(accuracy_score(y, y_pred))

y_pred = lda.predict(X)
print("accuracy_score_lda")
print(accuracy_score(y, y_pred))

y_pred = qda.predict(X)
print("accuracy_score_qda")
print(accuracy_score(y, y_pred))

#AUC

from sklearn import metrics

y_pred = lr.predict(X)
fpr, tpr, thresholds = metrics.roc_curve(y, y_pred)
print("AUC lr")
print(metrics.auc(fpr,tpr))

y_pred = lda.predict(X)
fpr, tpr, thresholds = metrics.roc_curve(y, y_pred)
print("AUC lda")
print(metrics.auc(fpr,tpr))

y_pred = qda.predict(X)
fpr, tpr, thresholds = metrics.roc_curve(y, y_pred)
print("AUC qda")
print(metrics.auc(fpr,tpr))

#11 ROC CURVE
from sklearn import metrics
y_pred = lr.predict(X)
fpr_lr, tpr_lr, thresholds = metrics.roc_curve(y, y_pred)
roc_auc_lr = metrics.auc(fpr_lr, tpr_lr)

y_pred = lda.predict(X)
fpr_lda, tpr_lda, thresholds = metrics.roc_curve(y, y_pred)
roc_auc_lda = metrics.auc(fpr_lda, tpr_lda)

y_pred = qda.predict(X)
fpr_qda, tpr_qda, thresholds = metrics.roc_curve(y, y_pred)
roc_auc_qda = metrics.auc(fpr_qda, tpr_qda)

#Plot
import matplotlib.pyplot as plt
plt.figure(2,figsize=(5,5))
plt.title('Receiver Operating Characteristic')
plt.plot(fpr_lr, tpr_lr, 'b', label = 'AUC = %0.2f' % roc_auc_lr)
plt.plot(fpr_lda, tpr_lda, 'b', label = 'AUC = %0.2f' % roc_auc_lda)
plt.plot(fpr_qda, tpr_qda, 'b', label = 'AUC = %0.2f' % roc_auc_qda)



Income  Limit  Rating  Cards  Age  Education  Gender Student Married  \
0   14.891   3606     283      2   34         11    Male      No     Yes   
1  106.025   6645     483      3   82         15  Female     Yes     Yes   
2  104.593   7075     514      4   71         11    Male      No      No   
3  148.924   9504     681      3   36         11  Female      No      No   
4   55.882   4897     357      2   68         16    Male      No     Yes   

   Ethnicity  Balance  
0  Caucasian      333  
1      Asian      903  
2      Asian      580  
3      Asian      964  
4  Caucasian      331

           Income         Limit      Rating       Cards         Age  \
count  400.000000    400.000000  400.000000  400.000000  400.000000   
mean    45.218885   4735.600000  354.940000    2.957500   55.667500   
std     35.244273   2308.198848  154.724143    1.371275   17.249807   
min     10.354000    855.000000   93.000000    1.000000   23.000000   
25%     21.007250   3088.000000  247.250000    2.000000   41.750000   
50%     33.115500   4622.500000  344.000000    3.000000   56.000000   
75%     57.470750   5872.750000  437.250000    4.000000   70.000000   
max    186.634000  13913.000000  982.000000    9.000000   98.000000   

        Education      Balance  
count  400.000000   400.000000  
mean    13.450000   520.015000  
std      3.125207   459.758877  
min      5.000000     0.000000  
25%     11.000000    68.750000  
50%     14.000000   459.500000  
75%     16.000000   863.000000  
max     20.000000  1999.000000  


<Figure size 2200x2200 with 0 Axes>

Text(0,0.5,'Balance vs Income')

Text(0,0.5,'Balance vs Limit')

Text(0,0.5,'Balance vs Rating')

Text(0,0.5,'Balance vs Cards')

Text(0,0.5,'Balance vs Age')

Text(0,0.5,'Balance vs Education')

Text(0,0.5,'Gender vs Education')

Text(0,0.5,'Student vs Education')

Text(0,0.5,'Married vs Education')

Text(0,0.5,'Ethnicity vs Education')

Income  Limit  Rating  Cards  Age  Education
0   14.891   3606     283      2   34         11
1  106.025   6645     483      3   82         15
2  104.593   7075     514      4   71         11
3  148.924   9504     681      3   36         11
4   55.882   4897     357      2   68         16

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

[-0.81363578]
[[-0.00950572  0.00499434 -0.05897994  0.11851539 -0.05977501 -0.35404606]]


LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariance=False, store_covariances=None, tol=0.0001)

y_pred_lr_1:
[0]
y_pred_lda_1:
[0]
y_pred_qda_1:
[0]
y_pred_lr_2:
[1]
y_pred_lda_2:
[1]
y_pred_qda_2:
[1]
confusion_matrix_lr
[[390   1]
 [  6   3]]
confusion_matrix_lda
[[383   8]
 [  4   5]]
confusion_matrix_qda
[[390   1]
 [  2   7]]
accuracy_score_lr
0.9825
accuracy_score_lda
0.97
accuracy_score_qda
0.9925
AUC lr
0.6653878942881499
AUC lda
0.7675475987496447
AUC qda
0.8876101165103721


<Figure size 500x500 with 0 Axes>

Text(0.5,1,'Receiver Operating Characteristic')

- From the dataset `Credit.csv`, the variable `Student` is extracted and saved as `Student`. 
- The number of observations in `Student` is saved as `population_size`.
- `Student` is factorized and I have computed the proportion of "students" and saved it as `true_p`. 

- The following simple logistic regression model is considered

$$ \mathrm{Pr}(\mathrm{Student = Yes}) = \frac{e^{\beta}}{1 + e^{\beta}}. $$

- The objective is to estimate $\beta$ by manipulating the likelihood of the model.

- A variable `sample_size` $=100$ is defined. i have taken samples `sample_size` number of observations from `Student` and called it `sample`.
- A function is defined and called `likelihood` which takes one argument `beta` and computes the likelihood of `beta` based on the `sample`.  
- I have randomly generate $50$ numbers from the **continuous uniform** distribution $U[-5;5]$. These numbers are saved as `beta_candidate`.
- Using the `likelihood` function defined before, the likelihood of `beta_candidate` is computed and saved as `likelihood_candidate`. Then, I have ploted the `likelihood_candidate` versus `beta_candidate`.
- Based on the chosen `beta_candidate`, the `true_p` is estimated (or $\mathrm{Pr}(\mathrm{Student = Yes})$ ).

In [3]:
import pandas as pd
#2 Load the Data
filename = 'data/Credit.csv'
Credit = pd.read_csv(filename, usecols=[1, 2, 3,4,5,6,7,8,9,10,11])
Credit.head()
students = Credit['Student']
print(students.describe())
population_size=400
#3
students['students_factorize'] = students.factorize()[0]

no=0
yes=0
for i in students['students_factorize']:
  if i==0:
    no=no+1
  else:
    yes=yes+1
proportion=yes/no
print("proportion")
print(proportion)

#4 take 100 samples
import random
import numpy as np
sample_size=50
sample=np.random.choice(students,size=sample_size)
#5 
import pandas as pd
import math
def likelihood(beta):
    p_i=(np.exp(beta))/(1+np.exp(beta))
    like=math.pow(p_i,sample)*(math.pow(1-p_i,1-sample))
    return like
#6
beta_candidate=np.random.uniform(-5,5,size=50)

Income  Limit  Rating  Cards  Age  Education  Gender Student Married  \
0   14.891   3606     283      2   34         11    Male      No     Yes   
1  106.025   6645     483      3   82         15  Female     Yes     Yes   
2  104.593   7075     514      4   71         11    Male      No      No   
3  148.924   9504     681      3   36         11  Female      No      No   
4   55.882   4897     357      2   68         16    Male      No     Yes   

   Ethnicity  Balance  
0  Caucasian      333  
1      Asian      903  
2      Asian      580  
3      Asian      964  
4  Caucasian      331

count     400
unique      2
top        No
freq      360
Name: Student, dtype: object
proportion
0.1111111111111111


C:\Users\farzad\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
